import { AuthProvider } from "../hook/AuthProvider"
import { ReduxProvider } from "../redux/ReduxProvider"
import { Inter } from "next/font/google"
import { Metadata } from "next/types"
import { ToastContainer } from "react-toastify"

import "react-toastify/dist/ReactToastify.css"
import "./global.scss"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Apec ELearning",
    description: "Generated by Apec Team",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body
                className={inter.className}
                style={{ width: "100vw", overflowX: "hidden" }}
            >
                <ReduxProvider>
                    <AuthProvider />
                    {children}
                </ReduxProvider>
                <ToastContainer/>
            </body>
        </html>
    )
}
